# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dabe35de6c537f31cbfb7847750ad7e5ef3a1efe04200533e53484a2b8af556c9a25887967d2c1af849e27002be196880321fba18a3486e2b9fa3df50b6b45c4

test:
  secret_key_base: a9aea6f80049437655aefdcaa4de0288e9d9fd1f86bf0aec30dc2e22696f223469d6740968cf394bde381e0b35ff9f673d0c5396ffca67f580d1412520adfdc7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
